import json
PG={}
PG["over-ons"]={
"en":("About us","<p>At Veloxity, we believe you deserve a moment of rest every day. No complicated routines, just 15 minutes of warmth and relaxation, at home on the sofa.</p><p>That's why we select comfort products that are easy to use, cordless and noticeable right away. We test every product ourselves before it goes into our shop.</p><h3>What we stand for</h3><ul><li><strong>Fast delivery:</strong> at your door within 2–5 working days</li><li><strong>30-day comfort guarantee:</strong> not happy? Send it back</li><li><strong>Personal service:</strong> a real person by email and WhatsApp</li></ul><p>Veloxity · [Adres] · Chamber of Commerce [nummer] · VAT ID [nummer]</p>"),
"de":("Über uns","<p>Bei Veloxity glauben wir, dass du dir jeden Tag einen Moment der Ruhe verdienst. Keine komplizierten Routinen, sondern 15 Minuten Wärme und Entspannung, bequem zu Hause auf dem Sofa.</p><p>Deshalb wählen wir Komfortprodukte aus, die einfach zu bedienen, kabellos und sofort spürbar sind. Jedes Produkt testen wir selbst, bevor es in unseren Shop kommt.</p><h3>Wofür wir stehen</h3><ul><li><strong>Schnelle Lieferung:</strong> innerhalb von 2–5 Werktagen bei dir</li><li><strong>30 Tage Komfortgarantie:</strong> nicht zufrieden? Schick es zurück</li><li><strong>Persönlicher Service:</strong> ein echter Mensch per E-Mail und WhatsApp</li></ul><p>Veloxity · [Adres] · Handelsregister (KvK) [nummer] · USt-IdNr. [nummer]</p>"),
"fr":("À propos","<p>Chez Veloxity, nous pensons que vous méritez chaque jour un moment de repos. Pas de routine compliquée, juste 15 minutes de chaleur et de détente, confortablement installé dans votre canapé.</p><p>C'est pourquoi nous sélectionnons des produits de confort faciles à utiliser, sans fil et efficaces dès la première utilisation. Nous testons nous-mêmes chaque produit avant de le proposer.</p><h3>Nos engagements</h3><ul><li><strong>Livraison rapide :</strong> chez vous en 2 à 5 jours ouvrés</li><li><strong>Garantie confort de 30 jours :</strong> pas satisfait ? Renvoyez-le</li><li><strong>Service personnalisé :</strong> une vraie personne par e-mail et WhatsApp</li></ul><p>Veloxity · [Adres] · N° d'entreprise (KvK) [nummer] · N° TVA [nummer]</p>")}
PG["veelgestelde-vragen"]={
"en":("FAQ","<h3>How quickly will my order be delivered?</h3><p>Your order is delivered within 2–5 working days in the Netherlands and Belgium. You'll receive a tracking code as soon as your parcel is on its way.</p><h3>Is it safe to use?</h3><p>Yes. Our devices switch off automatically after 15 minutes and have several heat levels. Start on the lowest level. Do not use on an open wound, during pregnancy, with a pacemaker or with reduced skin sensation. In doubt? Consult your GP first.</p><h3>How long does the battery last?</h3><p>A full battery lasts about 2–3 sessions of 15 minutes. Charging via USB-C takes about 2–3 hours.</p><h3>Will the knee massager fit my knee?</h3><p>The wrap has an adjustable Velcro strap and fits most knees. For larger knees or thighs there is an <a href=\"/products/xl-verlengband\">XL extension strap</a>.</p><h3>Can I return my order?</h3><p>Yes. You have a statutory 14-day withdrawal period. On top of that, we offer a 30-day comfort guarantee. See <a href=\"/pages/verzending-retour\">Shipping &amp; returns</a>.</p><h3>How can I pay?</h3><p>With iDEAL, Bancontact, credit card, Klarna or PayPal.</p><h3>Is this a medical device?</h3><p>No. Our products are intended for comfort and relaxation. They do not replace medical advice or treatment.</p>"),
"de":("Häufige Fragen","<h3>Wie schnell wird meine Bestellung geliefert?</h3><p>Deine Bestellung wird innerhalb von 2–5 Werktagen geliefert. Sobald dein Paket unterwegs ist, erhältst du eine Sendungsverfolgungsnummer.</p><h3>Ist die Anwendung sicher?</h3><p>Ja. Unsere Geräte schalten sich nach 15 Minuten automatisch ab und haben mehrere Wärmestufen. Beginne mit der niedrigsten Stufe. Nicht auf offenen Wunden, während der Schwangerschaft, mit Herzschrittmacher oder bei vermindertem Hautempfinden verwenden. Im Zweifel frage zuerst deinen Hausarzt.</p><h3>Wie lange hält der Akku?</h3><p>Ein voller Akku reicht für etwa 2–3 Anwendungen à 15 Minuten. Das Laden per USB-C dauert etwa 2–3 Stunden.</p><h3>Passt das Knie-Massagegerät an mein Knie?</h3><p>Die Manschette hat einen verstellbaren Klettverschluss und passt an die meisten Knie. Für größere Knie oder Oberschenkel gibt es ein <a href=\"/products/xl-verlengband\">XL-Verlängerungsband</a>.</p><h3>Kann ich meine Bestellung zurückgeben?</h3><p>Ja. Du hast ein gesetzliches Widerrufsrecht von 14 Tagen. Zusätzlich bieten wir eine 30-Tage-Komfortgarantie. Siehe <a href=\"/pages/verzending-retour\">Versand &amp; Rückgabe</a>.</p><h3>Wie kann ich bezahlen?</h3><p>Mit Kreditkarte, Klarna, PayPal, iDEAL oder Bancontact.</p><h3>Ist das ein Medizinprodukt?</h3><p>Nein. Unsere Produkte dienen dem Komfort und der Entspannung. Sie ersetzen keine ärztliche Beratung oder Behandlung.</p>"),
"fr":("FAQ","<h3>Quel est le délai de livraison ?</h3><p>Votre commande est livrée en 2 à 5 jours ouvrés aux Pays-Bas et en Belgique. Vous recevez un numéro de suivi dès l'expédition de votre colis.</p><h3>L'utilisation est-elle sûre ?</h3><p>Oui. Nos appareils s'arrêtent automatiquement après 15 minutes et proposent plusieurs niveaux de chaleur. Commencez par le niveau le plus bas. Ne pas utiliser sur une plaie ouverte, pendant la grossesse, avec un stimulateur cardiaque ou en cas de sensibilité cutanée réduite. En cas de doute, consultez d'abord votre médecin.</p><h3>Quelle est l'autonomie de la batterie ?</h3><p>Une batterie pleine permet environ 2 à 3 séances de 15 minutes. La recharge via USB-C prend environ 2 à 3 heures.</p><h3>Le masseur de genou est-il adapté à mon genou ?</h3><p>Le manchon dispose d'une bande velcro réglable et convient à la plupart des genoux. Pour les genoux ou cuisses plus larges, il existe une <a href=\"/products/xl-verlengband\">rallonge XL</a>.</p><h3>Puis-je retourner ma commande ?</h3><p>Oui. Vous disposez d'un délai légal de rétractation de 14 jours. En plus, nous offrons une garantie confort de 30 jours. Voir <a href=\"/pages/verzending-retour\">Livraison &amp; retours</a>.</p><h3>Comment puis-je payer ?</h3><p>Par Bancontact, iDEAL, carte bancaire, Klarna ou PayPal.</p><h3>S'agit-il d'un dispositif médical ?</h3><p>Non. Nos produits sont destinés au confort et à la détente. Ils ne remplacent pas un avis ou un traitement médical.</p>")}
PG["verzending-retour"]={
"en":("Shipping & returns","<h3>Shipping</h3><ul><li>Free shipping to the Netherlands and Belgium</li><li>Delivery time: 2–5 working days</li><li>You'll receive a tracking code by email</li></ul><h3>Right of withdrawal (14 days)</h3><p>You have the right to withdraw from your purchase within 14 days of receipt without giving any reason. Let us know via [e-mailadres] or use the <a href=\"/pages/herroepingsformulier\">model withdrawal form</a>. You then return the product within 14 days. We will refund the purchase price, including the original shipping costs, within 14 days of your notification. The cost of returning the product is at your expense.</p><h3>30-day comfort guarantee</h3><p>In addition to your statutory withdrawal period, you can return a product up to 30 days after receipt if you're not satisfied. Contact us via [e-mailadres] and we'll sort it out together.</p><h3>Return address</h3><p>[Retouradres]. Please never send a return without contacting us first, so we can process your parcel correctly.</p>"),
"de":("Versand & Rückgabe","<h3>Versand</h3><ul><li>Kostenloser Versand in die Niederlande und nach Belgien</li><li>Lieferzeit: 2–5 Werktage</li><li>Du erhältst eine Sendungsverfolgungsnummer per E-Mail</li></ul><h3>Widerrufsrecht (14 Tage)</h3><p>Du hast das Recht, binnen 14 Tagen nach Erhalt ohne Angabe von Gründen deinen Kauf zu widerrufen. Teile uns dies per [e-mailadres] mit oder nutze das <a href=\"/pages/herroepingsformulier\">Muster-Widerrufsformular</a>. Du sendest das Produkt anschließend innerhalb von 14 Tagen zurück. Wir erstatten den Kaufpreis einschließlich der ursprünglichen Versandkosten innerhalb von 14 Tagen nach deiner Mitteilung. Die Kosten der Rücksendung trägst du.</p><h3>30 Tage Komfortgarantie</h3><p>Zusätzlich zu deinem gesetzlichen Widerrufsrecht kannst du ein Produkt bis zu 30 Tage nach Erhalt zurückgeben, wenn du nicht zufrieden bist. Kontaktiere uns über [e-mailadres] und wir finden gemeinsam eine Lösung.</p><h3>Rücksendeadresse</h3><p>[Retouradres]. Bitte sende nie etwas zurück, ohne uns vorher zu kontaktieren, damit wir dein Paket richtig bearbeiten können.</p>"),
"fr":("Livraison & retours","<h3>Livraison</h3><ul><li>Livraison gratuite aux Pays-Bas et en Belgique</li><li>Délai de livraison : 2 à 5 jours ouvrés</li><li>Vous recevez un numéro de suivi par e-mail</li></ul><h3>Droit de rétractation (14 jours)</h3><p>Vous avez le droit de vous rétracter de votre achat dans les 14 jours suivant sa réception, sans avoir à motiver votre décision. Informez-nous via [e-mailadres] ou utilisez le <a href=\"/pages/herroepingsformulier\">formulaire type de rétractation</a>. Vous renvoyez ensuite le produit dans les 14 jours. Nous vous remboursons le prix d'achat, frais de livraison initiaux compris, dans les 14 jours suivant votre notification. Les frais de renvoi sont à votre charge.</p><h3>Garantie confort de 30 jours</h3><p>En plus de votre droit légal de rétractation, vous pouvez retourner un produit jusqu'à 30 jours après réception si vous n'êtes pas satisfait. Contactez-nous via [e-mailadres] et nous trouverons une solution ensemble.</p><h3>Adresse de retour</h3><p>[Retouradres]. N'envoyez jamais de retour sans nous contacter au préalable, afin que nous puissions traiter correctement votre colis.</p>")}
PG["garantie"]={
"en":("Warranty","<p>All our products come with the <strong>statutory warranty</strong>: a product must do what you can reasonably expect of it. Is there a defect not caused by incorrect use? Then we'll repair or replace the product, or refund your money.</p><p>In addition, we offer a <strong>30-day comfort guarantee</strong>: if you're not satisfied, you can return the product within 30 days of receipt.</p><p>For a warranty claim, contact us via [e-mailadres] with your order number and a photo or video of the problem.</p>"),
"de":("Garantie","<p>Für alle unsere Produkte gilt die <strong>gesetzliche Gewährleistung</strong>: Ein Produkt muss das leisten, was du vernünftigerweise erwarten kannst. Liegt ein Mangel vor, der nicht auf falsche Anwendung zurückgeht, reparieren oder ersetzen wir das Produkt oder erstatten dir den Kaufpreis.</p><p>Zusätzlich bieten wir eine <strong>30-Tage-Komfortgarantie</strong>: Bist du nicht zufrieden, kannst du das Produkt innerhalb von 30 Tagen nach Erhalt zurücksenden.</p><p>Für einen Gewährleistungsfall kontaktiere uns über [e-mailadres] mit deiner Bestellnummer und einem Foto oder Video des Problems.</p>"),
"fr":("Garantie","<p>Tous nos produits bénéficient de la <strong>garantie légale</strong> : un produit doit fonctionner comme vous pouvez raisonnablement l'attendre. En cas de défaut qui n'est pas dû à une mauvaise utilisation, nous réparons ou remplaçons le produit, ou vous remboursons.</p><p>En plus, nous offrons une <strong>garantie confort de 30 jours</strong> : si vous n'êtes pas satisfait, vous pouvez retourner le produit dans les 30 jours suivant sa réception.</p><p>Pour une demande de garantie, contactez-nous via [e-mailadres] avec votre numéro de commande et une photo ou vidéo du problème.</p>")}
PG["herroepingsformulier"]={
"en":("Model withdrawal form","<p>(Complete and return this form only if you wish to withdraw from the contract.)</p><p>To: Veloxity, [Adres], [e-mailadres]</p><p>I/We* hereby give notice that I/We* withdraw from my/our* contract of sale of the following goods:</p><p>Ordered on*/received on*: ____________<br>Order number: ____________<br>Name of consumer(s): ____________<br>Address of consumer(s): ____________<br>Signature (only if this form is notified on paper): ____________<br>Date: ____________</p><p>* Delete as appropriate.</p>"),
"de":("Muster-Widerrufsformular","<p>(Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.)</p><p>An: Veloxity, [Adres], [e-mailadres]</p><p>Hiermit widerrufe(n) ich/wir* den von mir/uns* abgeschlossenen Vertrag über den Kauf der folgenden Waren:</p><p>Bestellt am*/erhalten am*: ____________<br>Bestellnummer: ____________<br>Name des/der Verbraucher(s): ____________<br>Anschrift des/der Verbraucher(s): ____________<br>Unterschrift (nur bei Mitteilung auf Papier): ____________<br>Datum: ____________</p><p>* Unzutreffendes streichen.</p>"),
"fr":("Formulaire type de rétractation","<p>(Veuillez compléter et renvoyer le présent formulaire uniquement si vous souhaitez vous rétracter du contrat.)</p><p>À l'attention de : Veloxity, [Adres], [e-mailadres]</p><p>Je/Nous* vous notifie/notifions* par la présente ma/notre* rétractation du contrat portant sur la vente du bien ci-dessous :</p><p>Commandé le*/reçu le* : ____________<br>Numéro de commande : ____________<br>Nom du (des) consommateur(s) : ____________<br>Adresse du (des) consommateur(s) : ____________<br>Signature (uniquement en cas de notification sur papier) : ____________<br>Date : ____________</p><p>* Rayez la mention inutile.</p>")}
PG["contact"]={
"en":("Contact","<p>Do you have a question? We're happy to help, usually within 24 hours on working days.</p><ul><li><strong>Email:</strong> [e-mailadres]</li><li><strong>WhatsApp:</strong> [nummer]</li></ul><p>Veloxity<br>[Adres]<br>Chamber of Commerce: [nummer]<br>VAT ID: [nummer]</p>"),
"de":("Kontakt","<p>Hast du eine Frage? Wir helfen dir gern, meist innerhalb von 24 Stunden an Werktagen.</p><ul><li><strong>E-Mail:</strong> [e-mailadres]</li><li><strong>WhatsApp:</strong> [nummer]</li></ul><p>Veloxity<br>[Adres]<br>Handelsregister (KvK): [nummer]<br>USt-IdNr.: [nummer]</p>"),
"fr":("Contact","<p>Une question ? Nous vous aidons avec plaisir, généralement sous 24 heures les jours ouvrés.</p><ul><li><strong>E-mail :</strong> [e-mailadres]</li><li><strong>WhatsApp :</strong> [nummer]</li></ul><p>Veloxity<br>[Adres]<br>N° d'entreprise (KvK) : [nummer]<br>N° TVA : [nummer]</p>")}
TH={ # theme texts: NL -> en,de,fr
"DE WELLNESSROUTINE VOOR THUIS":("YOUR WELLNESS ROUTINE AT HOME","DEINE WELLNESS-ROUTINE FÜR ZUHAUSE","VOTRE ROUTINE BIEN-ÊTRE À LA MAISON"),
"15 minuten warmte.<br>Elke dag.":("15 minutes of warmth.<br>Every day.","15 Minuten Wärme.<br>Jeden Tag.","15 minutes de chaleur.<br>Chaque jour."),
"Draadloze comfortproducten met warmte, rood licht en massage. Gewoon thuis op de bank, zonder gedoe.":("Cordless comfort products with heat, red light and massage. Simply at home on the sofa, no hassle.","Kabellose Komfortprodukte mit Wärme, Rotlicht und Massage. Einfach zu Hause auf dem Sofa, ganz ohne Aufwand.","Des produits de confort sans fil avec chaleur, lumière rouge et massage. Tout simplement dans votre canapé, sans complication."),
"Ontdek de knie-massager":("Discover the knee massager","Entdecke das Knie-Massagegerät","Découvrir le masseur de genou"),
"Bekijk alle producten":("View all products","Alle Produkte ansehen","Voir tous les produits"),
"✓ Levering in 2–5 werkdagen":("✓ Delivery in 2–5 working days","✓ Lieferung in 2–5 Werktagen","✓ Livraison en 2 à 5 jours ouvrés"),
"✓ 30 dagen comfortgarantie":("✓ 30-day comfort guarantee","✓ 30 Tage Komfortgarantie","✓ Garantie confort de 30 jours"),
"✓ Veilig betalen met iDEAL &amp; Bancontact":("✓ Secure payment","✓ Sicher bezahlen","✓ Paiement sécurisé"),
"Onze bestsellers":("Our bestsellers","Unsere Bestseller","Nos best-sellers"),"Alles bekijken":("View all","Alle ansehen","Tout voir"),
"Een moment voor jezelf":("A moment for yourself","Ein Moment für dich","Un moment pour vous"),
"Stijve knieën 's ochtends, een gespannen nek na een dag achter het scherm, vermoeide ogen. Bij Veloxity geloven we dat comfort niet ingewikkeld hoeft te zijn. Doe het om, kies je stand en ontspan 15 minuten.":("Stiff knees in the morning, a tense neck after a day behind the screen, tired eyes. At Veloxity, we believe comfort doesn't have to be complicated. Put it on, choose your setting and relax for 15 minutes.","Steife Knie am Morgen, ein verspannter Nacken nach einem Tag am Bildschirm, müde Augen. Bei Veloxity glauben wir, dass Komfort nicht kompliziert sein muss. Anlegen, Stufe wählen und 15 Minuten entspannen.","Genoux raides le matin, nuque tendue après une journée devant l'écran, yeux fatigués. Chez Veloxity, nous pensons que le confort n'a pas à être compliqué. Mettez-le, choisissez votre niveau et détendez-vous 15 minutes."),
"Over ons":("About us","Über uns","À propos"),
"Comfortsets: samen voordeliger":("Comfort sets: better value together","Komfort-Sets: zusammen günstiger","Coffrets confort : moins chers ensemble"),"Alle sets":("All sets","Alle Sets","Tous les coffrets"),
"Probeer het zonder risico":("Try it risk-free","Ohne Risiko ausprobieren","Essayez sans risque"),
"Niet tevreden? Stuur je product binnen 30 dagen terug. Bovenop je wettelijke 14 dagen bedenktijd.":("Not happy? Return your product within 30 days. On top of your statutory 14-day withdrawal period.","Nicht zufrieden? Schick dein Produkt innerhalb von 30 Tagen zurück. Zusätzlich zu deinem gesetzlichen 14-tägigen Widerrufsrecht.","Pas satisfait ? Renvoyez votre produit sous 30 jours. En plus de votre droit légal de rétractation de 14 jours."),
"Verzending & retour":("Shipping & returns","Versand & Rückgabe","Livraison & retours"),
"Gratis verzending in Nederland & België":("Free shipping to the Netherlands & Belgium","Kostenloser Versand in die Niederlande & nach Belgien","Livraison gratuite aux Pays-Bas et en Belgique"),
"Levering in 2–5 werkdagen":("Delivery in 2–5 working days","Lieferung in 2–5 Werktagen","Livraison en 2 à 5 jours ouvrés"),
"30 dagen comfortgarantie":("30-day comfort guarantee","30 Tage Komfortgarantie","Garantie confort de 30 jours"),
"Blijf op de hoogte":("Stay in the loop","Bleib auf dem Laufenden","Restez informé"),
"Ontvang als eerste nieuwe producten, aanbiedingen en tips voor je dagelijkse comfortroutine.":("Be the first to hear about new products, offers and tips for your daily comfort routine.","Erfahre als Erste(r) von neuen Produkten, Angeboten und Tipps für deine tägliche Komfortroutine.","Soyez les premiers informés des nouveautés, offres et conseils pour votre routine confort."),
"Aanmelden":("Sign up","Anmelden","S'inscrire"),
"Deze pagina bestaat niet (meer)":("This page doesn't exist (anymore)","Diese Seite gibt es nicht (mehr)","Cette page n'existe pas (ou plus)"),
"De link klopt misschien niet, of de pagina is verplaatst. Geen zorgen: hieronder vind je onze producten.":("The link may be wrong, or the page has moved. No worries: you'll find our products below.","Der Link ist vielleicht falsch oder die Seite wurde verschoben. Keine Sorge: Unten findest du unsere Produkte.","Le lien est peut-être erroné ou la page a été déplacée. Pas d'inquiétude : vous trouverez nos produits ci-dessous."),
"Verder winkelen":("Continue shopping","Weiter einkaufen","Continuer mes achats"),"Misschien iets voor jou":("You might like","Vielleicht etwas für dich","Cela pourrait vous plaire"),
"Verstuur bericht":("Send message","Nachricht senden","Envoyer le message"),
"Veloxity opent binnenkort":("Veloxity is opening soon","Veloxity öffnet bald","Veloxity ouvre bientôt"),
"Laat je e-mailadres achter en hoor als eerste wanneer we live gaan.":("Leave your email address and be the first to know when we launch.","Hinterlass deine E-Mail-Adresse und erfahre als Erste(r), wann wir starten.","Laissez votre adresse e-mail et soyez les premiers informés de notre lancement."),
"Houd me op de hoogte":("Keep me posted","Halte mich auf dem Laufenden","Tenez-moi informé"),
"Winkelwagen":("Cart","Warenkorb","Panier"),"Maak je routine compleet":("Complete your routine","Vervollständige deine Routine","Complétez votre routine"),
"Collecties":("Collections","Kollektionen","Collections"),"Meer informatie":("More information","Mehr Informationen","Plus d'informations"),
"Past hier goed bij":("Goes well with","Passt gut dazu","Se marie bien avec"),
"✓ Gratis verzending in NL &amp; BE<br>✓ Levering in 2–5 werkdagen<br>✓ 30 dagen comfortgarantie<br>✓ Veilig betalen met iDEAL, Bancontact of Klarna":("✓ Free shipping to NL &amp; BE<br>✓ Delivery in 2–5 working days<br>✓ 30-day comfort guarantee<br>✓ Secure payment","✓ Kostenloser Versand in die NL &amp; nach BE<br>✓ Lieferung in 2–5 Werktagen<br>✓ 30 Tage Komfortgarantie<br>✓ Sicher bezahlen","✓ Livraison gratuite NL &amp; BE<br>✓ Livraison en 2 à 5 jours ouvrés<br>✓ Garantie confort de 30 jours<br>✓ Paiement sécurisé")}
T=json.load(open("vertalingen_deel1.json"))
T["pages"]={h:{l:{"title":t,"body":b} for l,(t,b) in v.items()} for h,v in PG.items()}
T["theme"]={nl:{"en":e,"de":d,"fr":f} for nl,(e,d,f) in TH.items()}
json.dump(T,open("vertalingen.json","w"),ensure_ascii=False,indent=1)
import os; os.remove("vertalingen_deel1.json")
print(len(T["pages"]),len(T["theme"]))
