import json
NOTE={
 "en":"This is a comfort and relaxation product, not a medical device. If you have complaints, please consult your GP or physiotherapist. Do not use on open wounds, during pregnancy or with a pacemaker.",
 "de":"Dies ist ein Komfort- und Entspannungsprodukt, kein Medizinprodukt. Bei Beschwerden wende dich bitte an deinen Hausarzt oder Physiotherapeuten. Nicht auf offenen Wunden, während der Schwangerschaft oder mit Herzschrittmacher verwenden.",
 "fr":"Ceci est un produit de confort et de détente, pas un dispositif médical. En cas de douleurs, consultez votre médecin ou kinésithérapeute. Ne pas utiliser sur une plaie ouverte, pendant la grossesse ou avec un stimulateur cardiaque."}
H={"en":("Why you'll love it","How it works","In the box"),"de":("Warum du es lieben wirst","So funktioniert es","Im Lieferumfang"),"fr":("Pourquoi vous allez l'adorer","Comment ça marche","Contenu de la boîte")}
def body(l,intro,bul,how,box,note=None):
    a,b,c=H[l]
    return (f"<p>{intro}</p><h3>{a}</h3><ul>"+"".join(f"<li>{x}</li>" for x in bul)+f"</ul><h3>{b}</h3><ol>"+"".join(f"<li>{x}</li>" for x in how)+f"</ol><h3>{c}</h3><p>{box}</p><p><em>{note or NOTE[l]}</em></p>")
T={"products":{},"collections":{},"pages":{},"menu":{},"theme":{}}
P=T["products"]
P["knie-massager"]={
 "en":{"title":"Cordless Knee Massager with Heat & Red Light","options":{"Aantal":"Quantity","1 stuk":"1 piece","2 stuks – bespaar €29,95":"2 pieces – save €29.95","3 stuks – bespaar €69,90":"3 pieces – save €69.90"},
  "seo_title":"Cordless Knee Massager with Heat & Red Light","seo_description":"15 minutes of heat, red light and massage for your knees, at home on the sofa. Cordless, 3 settings, 30-day comfort guarantee.",
  "body":body("en","Give your knees 15 minutes of warmth and rest every day. This cordless wrap combines soothing heat, gentle red light and vibration massage, right at home on the sofa.",
   ["Three comfort functions in one: heat (3 levels), red light and vibration (3 levels)","Cordless and rechargeable via USB-C, no cable in the way","Adjustable Velcro strap: fits knee, elbow and shoulder","Automatic shut-off after 15 minutes for carefree relaxation","Quiet enough to watch TV or read"],
   ["Fully charge the massager via USB-C","Wrap it around your knee and close the Velcro","Choose your heat and vibration level and relax for 15 minutes"],"1× knee massager, 1× USB-C cable, 1× manual (NL/EN)")},
 "de":{"title":"Kabelloses Knie-Massagegerät mit Wärme & Rotlicht","options":{"Aantal":"Anzahl","1 stuk":"1 Stück","2 stuks – bespaar €29,95":"2 Stück – spare 29,95 €","3 stuks – bespaar €69,90":"3 Stück – spare 69,90 €"},
  "seo_title":"Kabelloses Knie-Massagegerät mit Wärme & Rotlicht","seo_description":"15 Minuten Wärme, Rotlicht und Massage für deine Knie, bequem auf dem Sofa. Kabellos, 3 Stufen, 30 Tage Komfortgarantie.",
  "body":body("de","Gönne deinen Knien jeden Tag 15 Minuten Wärme und Ruhe. Diese kabellose Manschette kombiniert wohltuende Wärme, sanftes Rotlicht und Vibrationsmassage, ganz entspannt zu Hause auf dem Sofa.",
   ["Drei Komfortfunktionen in einem: Wärme (3 Stufen), Rotlicht und Vibration (3 Stufen)","Kabellos und per USB-C aufladbar, kein Kabel im Weg","Verstellbarer Klettverschluss: passt an Knie, Ellenbogen und Schulter","Automatische Abschaltung nach 15 Minuten für sorgenfreie Entspannung","Leise genug zum Fernsehen oder Lesen"],
   ["Lade das Gerät vollständig per USB-C auf","Lege die Manschette um dein Knie und schließe den Klettverschluss","Wähle Wärme- und Vibrationsstufe und entspanne 15 Minuten"],"1× Knie-Massagegerät, 1× USB-C-Kabel, 1× Anleitung (NL/EN)")},
 "fr":{"title":"Masseur de genou sans fil avec chaleur et lumière rouge","options":{"Aantal":"Quantité","1 stuk":"1 pièce","2 stuks – bespaar €29,95":"2 pièces – économisez 29,95 €","3 stuks – bespaar €69,90":"3 pièces – économisez 69,90 €"},
  "seo_title":"Masseur de genou sans fil – chaleur et lumière rouge","seo_description":"15 minutes de chaleur, de lumière rouge et de massage pour vos genoux, confortablement dans votre canapé. Sans fil, 3 niveaux, garantie confort de 30 jours.",
  "body":body("fr","Offrez à vos genoux 15 minutes de chaleur et de repos chaque jour. Ce manchon sans fil associe une chaleur apaisante, une douce lumière rouge et un massage par vibration, tranquillement installé dans votre canapé.",
   ["Trois fonctions de confort en une : chaleur (3 niveaux), lumière rouge et vibration (3 niveaux)","Sans fil et rechargeable par USB-C, aucun câble qui gêne","Bande velcro réglable : s'adapte au genou, au coude et à l'épaule","Arrêt automatique après 15 minutes pour une détente en toute sérénité","Assez silencieux pour regarder la télé ou lire"],
   ["Chargez complètement le masseur via USB-C","Placez le manchon autour du genou et fermez le velcro","Choisissez le niveau de chaleur et de vibration et détendez-vous 15 minutes"],"1× masseur de genou, 1× câble USB-C, 1× notice (NL/EN)")}}
P["nek-schouder-massager"]={
 "en":{"title":"Shiatsu Neck & Shoulder Massager with Heat","seo_title":"Shiatsu Neck & Shoulder Massager with Heat","seo_description":"Kneading shiatsu massage and heat for neck and shoulders. For home, office and car.",
  "body":body("en","A stiff neck after a day behind the screen? Place this shiatsu massager around your neck and shoulders and let the kneading massage and soothing heat do their work.",
   ["Kneading shiatsu massage with 3 intensities","Heat function for extra relaxation","Hand loops so you control the pressure","Use it on the sofa, at the office or in the car (12V adapter)","Automatic shut-off after 15 minutes"],
   ["Place the massager around your neck or lower back","Put your hands through the loops and set the pressure","Choose your setting and turn the heat on or off"],"1× neck massager, 1× adapter, 1× car charger, 1× manual (NL/EN)")},
 "de":{"title":"Shiatsu Nacken- & Schultermassagegerät mit Wärme","seo_title":"Shiatsu Nackenmassagegerät mit Wärme","seo_description":"Knetende Shiatsu-Massage und Wärme für Nacken und Schultern. Für Zuhause, Büro und Auto.",
  "body":body("de","Ein steifer Nacken nach einem Tag am Bildschirm? Lege dieses Shiatsu-Massagegerät um Nacken und Schultern und lass die knetende Massage und die wohltuende Wärme wirken.",
   ["Knetende Shiatsu-Massage mit 3 Intensitäten","Wärmefunktion für zusätzliche Entspannung","Handschlaufen, damit du den Druck selbst bestimmst","Für Sofa, Büro oder Auto (12-V-Adapter)","Automatische Abschaltung nach 15 Minuten"],
   ["Lege das Gerät um deinen Nacken oder unteren Rücken","Stecke die Hände durch die Schlaufen und bestimme den Druck","Wähle deine Stufe und schalte die Wärme ein oder aus"],"1× Nackenmassagegerät, 1× Adapter, 1× Autoladegerät, 1× Anleitung (NL/EN)")},
 "fr":{"title":"Masseur shiatsu cou et épaules avec chaleur","seo_title":"Masseur shiatsu cou et épaules avec chaleur","seo_description":"Massage shiatsu pétrissant et chaleur pour le cou et les épaules. À la maison, au bureau et en voiture.",
  "body":body("fr","La nuque raide après une journée devant l'écran ? Placez ce masseur shiatsu autour du cou et des épaules et laissez le massage pétrissant et la chaleur apaisante agir.",
   ["Massage shiatsu pétrissant avec 3 intensités","Fonction chaleur pour encore plus de détente","Poignées pour doser vous-même la pression","À utiliser dans le canapé, au bureau ou en voiture (adaptateur 12 V)","Arrêt automatique après 15 minutes"],
   ["Placez le masseur autour du cou ou du bas du dos","Glissez les mains dans les poignées et réglez la pression","Choisissez le mode et activez ou non la chaleur"],"1× masseur cou, 1× adaptateur, 1× chargeur voiture, 1× notice (NL/EN)")}}
P["oogmassager"]={
 "en":{"title":"Eye Massager with Heat & Bluetooth Music","seo_title":"Eye Massager with Heat & Bluetooth","seo_description":"Heat, air-pressure massage and music for tired eyes after a day behind the screen.",
  "body":body("en","After a long day behind the screen, your eyes deserve a moment of rest. This eye massager combines warmth, gentle air-pressure massage and your own relaxing music via Bluetooth.",
   ["Soothing warmth around your eyes","Gentle air-pressure and vibration massage with 5 modes","Play your own music or meditation via Bluetooth","Foldable and rechargeable, ideal for travel","Automatic shut-off after 15 minutes"],
   ["Charge the eye massager via USB-C","Put it on and adjust the strap","Choose a mode, connect your phone and relax"],"1× eye massager, 1× USB-C cable, 1× storage bag, 1× manual (NL/EN)")},
 "de":{"title":"Augenmassagegerät mit Wärme & Bluetooth-Musik","seo_title":"Augenmassagegerät mit Wärme & Bluetooth","seo_description":"Wärme, Luftdruckmassage und Musik für müde Augen nach einem Tag am Bildschirm.",
  "body":body("de","Nach einem langen Tag am Bildschirm haben deine Augen eine Pause verdient. Dieses Augenmassagegerät kombiniert Wärme, sanfte Luftdruckmassage und deine eigene entspannende Musik per Bluetooth.",
   ["Wohltuende Wärme rund um die Augen","Sanfte Luftdruck- und Vibrationsmassage mit 5 Modi","Eigene Musik oder Meditation per Bluetooth hören","Faltbar und aufladbar, ideal für unterwegs","Automatische Abschaltung nach 15 Minuten"],
   ["Lade das Gerät per USB-C auf","Setze es auf und stelle das Band ein","Wähle einen Modus, verbinde dein Handy und entspanne"],"1× Augenmassagegerät, 1× USB-C-Kabel, 1× Aufbewahrungstasche, 1× Anleitung (NL/EN)")},
 "fr":{"title":"Masseur pour les yeux avec chaleur et musique Bluetooth","seo_title":"Masseur pour les yeux – chaleur et Bluetooth","seo_description":"Chaleur, massage par pression d'air et musique pour les yeux fatigués après une journée devant l'écran.",
  "body":body("fr","Après une longue journée devant l'écran, vos yeux méritent une pause. Ce masseur associe chaleur, massage doux par pression d'air et votre propre musique relaxante via Bluetooth.",
   ["Une chaleur apaisante autour des yeux","Massage doux par pression d'air et vibration, 5 modes","Écoutez votre musique ou méditation via Bluetooth","Pliable et rechargeable, idéal en voyage","Arrêt automatique après 15 minutes"],
   ["Chargez le masseur via USB-C","Mettez-le et ajustez la bande","Choisissez un mode, connectez votre téléphone et détendez-vous"],"1× masseur pour les yeux, 1× câble USB-C, 1× pochette, 1× notice (NL/EN)")}}
def setbody(l,save,los,inner):
    return f"<p><strong>{save}</strong> {los}</p><p>{inner}</p><p><em>{NOTE[l]}</em></p>"
P["comfortset-knie-nek"]={
 "en":{"title":"Comfort Set: Knee + Neck","seo_title":"Comfort Set Knee + Neck","seo_description":"Knee massager and neck massager together at a lower price.",
  "body":setbody("en","You save €24.95","compared to buying separately (€139.90).","Heat and massage for your knees and your neck and shoulders, cheaper together. This set contains 1× <a href='/products/knie-massager'>Cordless Knee Massager</a> and 1× <a href='/products/nek-schouder-massager'>Shiatsu Neck Massager</a>.")},
 "de":{"title":"Komfort-Set: Knie + Nacken","seo_title":"Komfort-Set Knie + Nacken","seo_description":"Knie- und Nackenmassagegerät zusammen günstiger.",
  "body":setbody("de","Du sparst 24,95 €","gegenüber dem Einzelkauf (139,90 €).","Wärme und Massage für Knie sowie Nacken und Schultern, zusammen günstiger. Dieses Set enthält 1× <a href='/products/knie-massager'>kabelloses Knie-Massagegerät</a> und 1× <a href='/products/nek-schouder-massager'>Shiatsu-Nackenmassagegerät</a>.")},
 "fr":{"title":"Coffret confort : genou + cou","seo_title":"Coffret confort genou + cou","seo_description":"Masseur de genou et masseur cou réunis à prix réduit.",
  "body":setbody("fr","Vous économisez 24,95 €","par rapport à l'achat séparé (139,90 €).","Chaleur et massage pour vos genoux ainsi que votre cou et vos épaules, moins cher ensemble. Ce coffret contient 1× <a href='/products/knie-massager'>masseur de genou sans fil</a> et 1× <a href='/products/nek-schouder-massager'>masseur shiatsu cou</a>.")}}
P["complete-comfort-routine"]={
 "en":{"title":"Complete Comfort Routine: Knee + Neck + Eyes","seo_title":"Complete Comfort Routine Set","seo_description":"Knee, neck and eye massager together in one great-value set.",
  "body":setbody("en","You save €49.90","compared to buying separately (€189.85).","Your complete relaxation routine in one set, and a lovely gift too. This set contains the <a href='/products/knie-massager'>Knee Massager</a>, the <a href='/products/nek-schouder-massager'>Neck Massager</a> and the <a href='/products/oogmassager'>Eye Massager</a>.")},
 "de":{"title":"Komplette Komfort-Routine: Knie + Nacken + Augen","seo_title":"Komplette Komfort-Routine Set","seo_description":"Knie-, Nacken- und Augenmassagegerät zusammen in einem günstigen Set.",
  "body":setbody("de","Du sparst 49,90 €","gegenüber dem Einzelkauf (189,85 €).","Deine komplette Entspannungsroutine in einem Set, und auch ein schönes Geschenk. Dieses Set enthält das <a href='/products/knie-massager'>Knie-Massagegerät</a>, das <a href='/products/nek-schouder-massager'>Nackenmassagegerät</a> und das <a href='/products/oogmassager'>Augenmassagegerät</a>.")},
 "fr":{"title":"Routine confort complète : genou + cou + yeux","seo_title":"Coffret routine confort complète","seo_description":"Masseurs genou, cou et yeux réunis dans un coffret avantageux.",
  "body":setbody("fr","Vous économisez 49,90 €","par rapport à l'achat séparé (189,85 €).","Votre routine détente complète en un seul coffret, et une belle idée cadeau. Ce coffret contient le <a href='/products/knie-massager'>masseur de genou</a>, le <a href='/products/nek-schouder-massager'>masseur cou</a> et le <a href='/products/oogmassager'>masseur pour les yeux</a>.")}}
P["xl-verlengband"]={
 "en":{"title":"XL Extension Strap for the Knee Massager","seo_title":"XL Extension Strap Knee Massager","seo_description":"20 cm extra length for a comfortable fit.","body":"<p>Extra 20 cm Velcro extension so the knee massager also fits comfortably around larger knees, thighs or shoulders.</p>"},
 "de":{"title":"XL-Verlängerungsband für das Knie-Massagegerät","seo_title":"XL-Verlängerungsband Knie-Massagegerät","seo_description":"20 cm zusätzliche Länge für eine bequeme Passform.","body":"<p>Zusätzliche 20 cm Klettverlängerung, damit das Knie-Massagegerät auch bequem um größere Knie, Oberschenkel oder Schultern passt.</p>"},
 "fr":{"title":"Rallonge XL pour le masseur de genou","seo_title":"Rallonge XL masseur de genou","seo_description":"20 cm de longueur en plus pour un ajustement confortable.","body":"<p>Rallonge velcro de 20 cm pour que le masseur de genou s'adapte aussi confortablement aux genoux plus larges, aux cuisses ou aux épaules.</p>"}}
LEDN={"en":"Cosmetic product. Do not use if you are sensitive to light, have epilepsy or take photosensitising medication. Results vary from person to person.",
 "de":"Kosmetisches Produkt. Nicht verwenden bei Lichtempfindlichkeit, Epilepsie oder lichtsensibilisierenden Medikamenten. Ergebnisse sind individuell verschieden.",
 "fr":"Produit cosmétique. Ne pas utiliser en cas de sensibilité à la lumière, d'épilepsie ou de médicaments photosensibilisants. Les résultats varient d'une personne à l'autre."}
P["led-gezichtsmasker"]={
 "en":{"title":"LED Light Therapy Face Mask (Red, Blue & Near-Infrared)","options":{"Aantal":"Quantity","1 stuk":"1 piece","2 stuks – bespaar €39,00":"2 pieces – save €39.00"},"seo_title":"LED Face Mask Red Light","seo_description":"LED light therapy mask for home: red, blue and near-infrared.",
  "body":body("en","Your own LED ritual at home: 10 minutes a day for radiant, well-cared-for skin.",["Red, blue and near-infrared light","Flexible silicone mask with a comfortable fit","Cordless and rechargeable","Automatic shut-off after 10 minutes"],["Cleanse your face","Put on the mask and choose a programme","Relax for 10 minutes"],"1× LED mask, 1× eye protection, 1× USB-C cable, 1× manual (NL/EN)",LEDN["en"])},
 "de":{"title":"LED-Lichttherapie-Gesichtsmaske (Rot, Blau & Nahinfrarot)","options":{"Aantal":"Anzahl","1 stuk":"1 Stück","2 stuks – bespaar €39,00":"2 Stück – spare 39,00 €"},"seo_title":"LED-Gesichtsmaske Rotlicht","seo_description":"LED-Lichttherapiemaske für Zuhause: Rot, Blau und Nahinfrarot.",
  "body":body("de","Dein eigenes LED-Ritual zu Hause: 10 Minuten am Tag für eine strahlende, gepflegte Haut.",["Rotes, blaues und nahinfrarotes Licht","Flexible Silikonmaske mit angenehmer Passform","Kabellos und aufladbar","Automatische Abschaltung nach 10 Minuten"],["Reinige dein Gesicht","Setze die Maske auf und wähle ein Programm","Entspanne 10 Minuten"],"1× LED-Maske, 1× Augenschutz, 1× USB-C-Kabel, 1× Anleitung (NL/EN)",LEDN["de"])},
 "fr":{"title":"Masque LED luminothérapie (rouge, bleu et proche infrarouge)","options":{"Aantal":"Quantité","1 stuk":"1 pièce","2 stuks – bespaar €39,00":"2 pièces – économisez 39,00 €"},"seo_title":"Masque LED lumière rouge","seo_description":"Masque de luminothérapie LED pour la maison : rouge, bleu et proche infrarouge.",
  "body":body("fr","Votre rituel LED à la maison : 10 minutes par jour pour une peau éclatante et soignée.",["Lumière rouge, bleue et proche infrarouge","Masque souple en silicone, confortable","Sans fil et rechargeable","Arrêt automatique après 10 minutes"],["Nettoyez votre visage","Mettez le masque et choisissez un programme","Détendez-vous 10 minutes"],"1× masque LED, 1× protection des yeux, 1× câble USB-C, 1× notice (NL/EN)",LEDN["fr"])}}
T["collections"]={
 "knie-gewrichten":{"en":("Knees & joints","<p>Heat, red light and massage for supple knees: 15 minutes a day, at home on the sofa.</p>"),"de":("Knie & Gelenke","<p>Wärme, Rotlicht und Massage für geschmeidige Knie: 15 Minuten am Tag, bequem auf dem Sofa.</p>"),"fr":("Genoux & articulations","<p>Chaleur, lumière rouge et massage pour des genoux souples : 15 minutes par jour, dans votre canapé.</p>")},
 "nek-schouders":{"en":("Neck & shoulders","<p>Release the tension of a long day with kneading massage and soothing heat.</p>"),"de":("Nacken & Schultern","<p>Lass die Anspannung eines langen Tages los, mit knetender Massage und wohltuender Wärme.</p>"),"fr":("Cou & épaules","<p>Relâchez les tensions d'une longue journée grâce au massage pétrissant et à une chaleur apaisante.</p>")},
 "ogen-ontspanning":{"en":("Eyes & relaxation","<p>A moment of nothing at all. Warmth and rest for tired eyes after a day behind the screen.</p>"),"de":("Augen & Entspannung","<p>Einfach mal nichts tun. Wärme und Ruhe für müde Augen nach einem Tag am Bildschirm.</p>"),"fr":("Yeux & détente","<p>Un moment rien qu'à vous. Chaleur et repos pour les yeux fatigués après une journée devant l'écran.</p>")},
 "comfortsets":{"en":("Comfort sets","<p>Your complete comfort routine in one set: better value than buying separately, and a lovely gift.</p>"),"de":("Komfort-Sets","<p>Deine komplette Komfortroutine in einem Set: günstiger als einzeln und ein schönes Geschenk.</p>"),"fr":("Coffrets confort","<p>Votre routine confort complète en un coffret : plus avantageux qu'à l'unité, et une belle idée cadeau.</p>")},
 "accessoires":{"en":("Accessories","<p>Handy extras for your comfort products.</p>"),"de":("Zubehör","<p>Praktische Extras für deine Komfortprodukte.</p>"),"fr":("Accessoires","<p>Des extras pratiques pour vos produits de confort.</p>")}}
T["menu"]={"Home":{"en":"Home","de":"Startseite","fr":"Accueil"},"Shop":{"en":"Shop","de":"Shop","fr":"Boutique"},
 "Knie & gewrichten":{"en":"Knees & joints","de":"Knie & Gelenke","fr":"Genoux & articulations"},"Nek & schouders":{"en":"Neck & shoulders","de":"Nacken & Schultern","fr":"Cou & épaules"},
 "Ogen & ontspanning":{"en":"Eyes & relaxation","de":"Augen & Entspannung","fr":"Yeux & détente"},"Accessoires":{"en":"Accessories","de":"Zubehör","fr":"Accessoires"},
 "Alle producten":{"en":"All products","de":"Alle Produkte","fr":"Tous les produits"},"Comfortsets":{"en":"Comfort sets","de":"Komfort-Sets","fr":"Coffrets confort"},
 "Veelgestelde vragen":{"en":"FAQ","de":"Häufige Fragen","fr":"FAQ"},"Contact":{"en":"Contact","de":"Kontakt","fr":"Contact"},
 "Over ons":{"en":"About us","de":"Über uns","fr":"À propos"},"Verzending & retour":{"en":"Shipping & returns","de":"Versand & Rückgabe","fr":"Livraison & retours"},
 "Garantie":{"en":"Warranty","de":"Garantie","fr":"Garantie"},"Herroepingsformulier":{"en":"Withdrawal form","de":"Widerrufsformular","fr":"Formulaire de rétractation"},"Zoeken":{"en":"Search","de":"Suche","fr":"Recherche"}}
json.dump(T,open("vertalingen_deel1.json","w"),ensure_ascii=False,indent=1)
print("ok", sum(len(v) for v in P.values()))
